### PR TITLE
IMAGE OPTIMISATION

### PR DESCRIPTION
**Pull request by Jaytru1997**

### CODE REVIEW

**Review by Denice-S — CHANGES_REQUESTED** [review]
Hi,   
 This looks great , the changed link in the footer to the thank you page works perfectly but could you please make the following changes and push your changes again?

1. For some reason when I view your code there is no longer a .gitignore file there. We have this file so that it doesn't upload vscode settings. Please could you either pull down from github again or you could just copy the file.

2. With the colours, please could you restrict the colours to what we have actually used in the styling of the document ( text/lines etc)  not including images, so from line 17 (Azure) to line 154(Maroon) are not being used and not needed so please remove these .

3. We are not using imgBot in this project, as juniors we want to be looking at image optimization ourselves and not using a bot, we also don't have a lot of images so it is not worth using. Please can you remove this.?

Thanks

**Comment by Jaytru1997** [comment]
Alrighty! Will get to it. Also, I must have misinterpreted the requirements for the colors ticket.

**Comment by Denice-S** [comment]
Hi Jay, 

Thanks for making these changes. However I noticed you have also made some changes to the navbar?. This is on a separate ticket and was not in the original pull request you made and is also nothing to do with the changes I was asking you to make. 

The navbar  needs changes made to it - it is now black and not white when you scroll which is great!!  BUT -
1. when you scroll away the links disappear completely and should not
2. The logo is animated - it is shifting position when you scroll and should not, it should stay in the same place
3. There is a gap between the navbar and the top of the screen when you scroll away. Please could you make these changes before I can merge .

I cannot merge this PR in yet with a navbar that needs changes made to it,  which is why in future maybe try and keep some PR separate , it will make it easier to close off your tickets (for example - if you hadn't started the navbar changes I could have merged in and closed off 3 tickets for you) . 

Any problems please give me a shout

**Comment by Jaytru1997** [comment]
Navbar fixed, kindly review pr.

**Comment by Denice-S** [comment]
Jay, 

The navbar is so much better!! 

Could you just put a bit more spacing around the  top and bottom of the  logo on the navbar, currently it is touching the top and bottom of the navbar and would look much better with a bit of spacing.?

**Comment by Jaytru1997** [comment]
Yay! Nav bar is better!

Alright will get on it.

Thanks for reviewing.

**Comment by Jaytru1997** [comment]
All Done! Kindly review pr

**Pull request merged**
