### PR TITLE
Made Navbar responsive and fix the text color of form.

### PR DESCRIPTION
**Pull request by CS-Aditya-Rawat**

### CODE REVIEW

**Comment by mateahoward** [comment]
Well done on this @CS-Aditya-Rawat :D I just have a tiny little request: 
Could you make our logo and the hamburger icon (the menu icon on mobile) vertically aligned? 

image

Just so they're on the same level if that makes sense :D  Otherwise, great work :D

**Comment by CS-Aditya-Rawat** [comment]
OK, I will!😀

**Comment by mateahoward** [comment]
Hey @CS-Aditya-Rawat, how are we doing with this? :D Do you think you'll have time to finish it off this week by any chance? 
Let me know how are you getting on :D Hope you're okay :)

**Comment by CS-Aditya-Rawat** [comment]
I have fixed the logo position but as you said not to use any extra javascript file for it just use CSS, so I have to again work on this from starting and right now my exam is going on. If you want this ticket completed soon so I can drop the ticket for another member because I can only give time after 20 Feb on projects.

**Pull request closed without merging**
